### ISSUE TITLE
Setup API Testing

### ISSUE THREAD

**Issue by DChan0319** [Bulls-Vs-Bears/api#14]
We will still use postman for manual testing, but i wanted to also use a javascript testing framework. I think i'm going to go with [Jest.js](https://jestjs.io/docs) for this one.

## Tasks:
- [ ] Research testing frameworks for javascript.
- [ ] Setup and install Jest.
- [ ] Create a test for POST /register endpoint inside /test/register
